# Generated by Django 3.0.3 on 2022-02-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_userpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
