# Generated by Django 3.0.3 on 2022-02-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_auto_20220224_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='birthdate',
            field=models.CharField(max_length=256),
        ),
    ]
